from __future__ import annotations

from copy import deepcopy

from segmentum.m226_maturity_audit import SEED_SET


def base_standardized_replays() -> dict[str, dict[str, object]]:
    replays = {
        "M2.21": {
            "milestone_id": "M2.21",
            "dimension": "narrative_grounding_robustness",
            "milestone_status": True,
            "freshness_status": True,
            "protocol_completeness": True,
            "current_round_replay_status": True,
            "gating_metrics_summary": {"artifact_schema_complete": True, "behavior_causality": True},
            "residual_risks": [],
            "blocking_issues": [],
            "score": 0.86,
            "evidence_origin": "current_round_replay",
            "legacy_evidence_used": False,
            "inherited_only_evidence": False,
            "holdout_data_used": False,
            "holdout_passed": None,
            "lexical_shortcut_dependency": False,
            "adapter_collapse_risk": False,
            "report_leakage": False,
            "false_consistency": False,
            "spurious_transfer": False,
            "causal_failure": False,
            "codebase_version": "test-sha",
            "seed_set": list(SEED_SET),
            "protocol_config": {"cycles": 24},
        },
        "M2.22": {
            "milestone_id": "M2.22",
            "dimension": "long_horizon_autonomy",
            "milestone_status": True,
            "freshness_status": True,
            "protocol_completeness": True,
            "current_round_replay_status": True,
            "gating_metrics_summary": {"artifact_schema_complete": True, "restart_continuity": True},
            "residual_risks": [],
            "blocking_issues": [],
            "score": 0.88,
            "evidence_origin": "current_round_replay",
            "legacy_evidence_used": False,
            "inherited_only_evidence": False,
            "holdout_data_used": False,
            "holdout_passed": None,
            "lexical_shortcut_dependency": False,
            "adapter_collapse_risk": False,
            "report_leakage": False,
            "false_consistency": False,
            "spurious_transfer": False,
            "causal_failure": False,
            "codebase_version": "test-sha",
            "seed_set": list(SEED_SET),
            "protocol_config": {"protocols": ["mixed_stress"]},
        },
        "M2.23": {
            "milestone_id": "M2.23",
            "dimension": "self_consistency_and_repair",
            "milestone_status": True,
            "freshness_status": True,
            "protocol_completeness": True,
            "current_round_replay_status": True,
            "gating_metrics_summary": {"artifact_schema_complete": True, "protocol_integrity": True, "repair_effectiveness": True},
            "residual_risks": [],
            "blocking_issues": [],
            "score": 0.87,
            "evidence_origin": "current_round_replay",
            "legacy_evidence_used": False,
            "inherited_only_evidence": False,
            "holdout_data_used": False,
            "holdout_passed": None,
            "lexical_shortcut_dependency": False,
            "adapter_collapse_risk": False,
            "report_leakage": False,
            "false_consistency": False,
            "spurious_transfer": False,
            "causal_failure": False,
            "codebase_version": "test-sha",
            "seed_set": list(SEED_SET),
            "protocol_config": {"scenario_count": 4},
        },
        "M2.24": {
            "milestone_id": "M2.24",
            "dimension": "functional_conscious_access",
            "milestone_status": True,
            "freshness_status": True,
            "protocol_completeness": True,
            "current_round_replay_status": True,
            "gating_metrics_summary": {"artifact_schema_complete": True, "semantic_report_leakage": True, "policy_causality_gain": True},
            "residual_risks": [],
            "blocking_issues": [],
            "score": 0.90,
            "evidence_origin": "current_round_replay",
            "legacy_evidence_used": False,
            "inherited_only_evidence": False,
            "holdout_data_used": False,
            "holdout_passed": None,
            "lexical_shortcut_dependency": False,
            "adapter_collapse_risk": False,
            "report_leakage": False,
            "false_consistency": False,
            "spurious_transfer": False,
            "causal_failure": False,
            "codebase_version": "test-sha",
            "seed_set": list(SEED_SET),
            "protocol_config": {"variants": ["full_workspace"]},
        },
        "M2.25": {
            "milestone_id": "M2.25",
            "dimension": "open_world_transfer",
            "milestone_status": True,
            "freshness_status": True,
            "protocol_completeness": True,
            "current_round_replay_status": True,
            "gating_metrics_summary": {"artifact_schema_complete": True, "unseen_world_transfer": True, "anti_shortcut": True, "core_trace_coverage": True},
            "residual_risks": [],
            "blocking_issues": [],
            "score": 0.89,
            "evidence_origin": "current_round_replay",
            "legacy_evidence_used": False,
            "inherited_only_evidence": False,
            "holdout_data_used": False,
            "holdout_passed": True,
            "lexical_shortcut_dependency": False,
            "adapter_collapse_risk": False,
            "report_leakage": False,
            "false_consistency": False,
            "spurious_transfer": False,
            "causal_failure": False,
            "codebase_version": "test-sha",
            "seed_set": list(SEED_SET),
            "protocol_config": {"holdout_worlds": ["holdout_a"], "pytest_tests": 4},
        },
    }
    return deepcopy(replays)
